export const ROUTES = {
    shop: {
        layout: '/',
        products: '/',
        product: '/product/:uuid',
        productDynamic: (uuid: string) => `/product/${uuid}`,
        cart: '/cart',
        blogs: '/blog',
        blog: '/blog/:id',
        restorePassword: '/restore',
    },
    account: {
        layout: '/account',
        me: '/account/me',
        address: '/account/address',
        orders: '/account/orders',
        order: '/account/orders/:uuid',
        orderDynamic: (uuid: string) => `/account/orders/${uuid}`,
        favorites: '/account/favorites',
    },
    admin: {
        layout: '/admin',
        users: '/admin/users/all',
        userStats: '/admin/users/stats',
        user: '/admin/users/:uuid',
        userDynamic: (uuid: string) => `/admin/users/${uuid}`,
        products: '/admin/products',
        product: '/admin/products/:uuid',
        productDynamic: (uuid: string) => `/admin/products/${uuid}`,
        createProduct: '/admin/create-product',
    },
    error: '*',
};
